module.exports = {
  apps: [
    {
      name: `fiatconnect`,
      script: 'build/src/index.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'localhost',
        REDISCLOUD_URL: process.env.REDISCLOUD_URL,
      },
      env_development: {
        NODE_ENV: process.env.NODE_ENV,
        SESSION_SECRET: process.env.SESSION_SECRET,
        AUTH_CONFIG_OPTION: process.env.AUTH_CONFIG_OPTION,
        PORT: process.env.PORT,
        REDISCLOUD_URL: process.env.REDISCLOUD_URL,
        RECEIVER_PRIVATE_KEY: process.env.RECEIVER_PRIVATE_KEY,
        SENDER_PRIVATE_KEY: process.env.SENDER_PRIVATE_KEY,
        COIN_MARKET_CAP_KEY: process.env.COIN_MARKET_CAP_KEY,
        COIN_MARKET_CAP_BASE_URL: process.env.COIN_MARKET_CAP_BASE_URL,
        DATABASE_USER: process.env.DATABASE_USER,
        DATABASE_PORT: process.env.DATABASE_PORT,
        DATABASE_URL: process.env.DATABASE_URL,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
        DATABASE_NAME: process.env.DATABASE_NAME,
      },
      env_staging: {
        NODE_ENV: process.env.NODE_ENV,
        SESSION_SECRET: process.env.SESSION_SECRET,
        AUTH_CONFIG_OPTION: process.env.AUTH_CONFIG_OPTION,
        PORT: process.env.PORT,
        REDISCLOUD_URL: process.env.REDISCLOUD_URL,
        RECEIVER_PRIVATE_KEY: process.env.RECEIVER_PRIVATE_KEY,
        SENDER_PRIVATE_KEY: process.env.SENDER_PRIVATE_KEY,
        COIN_MARKET_CAP_KEY: process.env.COIN_MARKET_CAP_KEY,
        COIN_MARKET_CAP_BASE_URL: process.env.COIN_MARKET_CAP_BASE_URL,
        DATABASE_USER: process.env.DATABASE_USER,
        DATABASE_PORT: process.env.DATABASE_PORT,
        DATABASE_URL: process.env.DATABASE_URL,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
        DATABASE_NAME: process.env.DATABASE_NAME,
      },
      env_production: {
        NODE_ENV: process.env.NODE_ENV,
        SESSION_SECRET: process.env.SESSION_SECRET,
        AUTH_CONFIG_OPTION: process.env.AUTH_CONFIG_OPTION,
        PORT: process.env.PORT,
        REDISCLOUD_URL: process.env.REDISCLOUD_URL,
        RECEIVER_PRIVATE_KEY: process.env.RECEIVER_PRIVATE_KEY,
        SENDER_PRIVATE_KEY: process.env.SENDER_PRIVATE_KEY,
        COIN_MARKET_CAP_KEY: process.env.COIN_MARKET_CAP_KEY,
        COIN_MARKET_CAP_BASE_URL: process.env.COIN_MARKET_CAP_BASE_URL,
        DATABASE_USER: process.env.DATABASE_USER,
        DATABASE_PORT: process.env.DATABASE_PORT,
        DATABASE_URL: process.env.DATABASE_URL,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
        DATABASE_NAME: process.env.DATABASE_NAME,
      },
    },
  ],
}
